name: analysis3
channels:
- coecms
- conda-forge
- accessnri
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/hh5/public/apps/cartopy-data/backgrounds
dependencies:
- python>=3.9
- pip
- sqlalchemy==1.4.46 ### cosima cookbook does not import with sqlalchemy 2
- libnetcdf>=4.7.4=mpi_openmpi* # pinned for solver stability
- coecms-nci
- cdo>=1.9.5 # pinned for solver stability
- hdf5
 #x basemap # Deprecated, see https://matplotlib.org/basemap/users/intro.html#deprecation-notice
 #x basemap-data-hires
- cartopy>=0.19 # pinned for solver stability
- dask
- distributed
- ipython
- iris
- netcdf4<=1.6.0 ### Workaround for https://github.com/pydata/xarray/issues/7079
- numpy>=1.21 # Mule dependency
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- jupyter
- notebook
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh<3.0.0 ### Bokeh 3 breaks geoviews
- datashader
- f90nml
- wrf-python>=1.3.4 ### Force update
- sympy
- sh
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- compliance-checker
- dataset
- xerces-c
- plotly
- zarr
- pytables
- nose
- ncdu
- cftime
- cfunits
- memory_profiler
- fs
- python-magic
- click_default_group
- regionmask
- rasterio
- gdal
- libgdal
- matplotlib
#- matplotlib>=3.5.2|<=3.4.3  # pinned to solve  https://github.com/matplotlib/matplotlib/issues/21917
- dreqpy
- pint<=0.19.2 ### pinned to fix https://github.com/Ouranosinc/xclim/issues/1216
- pycodestyle 
- nc-time-axis
- jq
- pvlib-python
- parcels
- siphon
- scikit-learn
- filelock
- gsw
- nb_conda_kernels
- poppler
- fiona
- hupper
- kealib
- mo_pack
- mule
- cf-units
- python-stratify
- nbdime
- eofs
- eccodes
- python-eccodes
- h5py
- line_profiler
- bottleneck
- jupyterlab
- dask-jobqueue
- jupyterlab_server
- docrep
- gifsicle
- jupyter_nbextensions_configurator
- nodejs
- cfgrib
- h5netcdf
- jupyter_contrib_nbextensions
- intake #==0.6.5 # pinned to downgrade until intake 0.6.6 issue is solved
- gridfill
- xgcm>0.5 # pinned for solver stability
- xrft
- doit
- pylint
- dusqlpg
- matplotlib-venn
- nchash
- umtools
- cosima-cookbook
- clef
- nccmp
- coecms-util
- yamanifest
- cmocean
- payu
- splitvar
- marineHeatWaves
- holoviews
- geoviews
- pytest-cov
- panel
- xrft
- git
- openmpi
- mpi4py
- palettable
- xlrd
- nccompress
- mdssdiff
- mnctools
- addmeta
- satpy
- statsmodels
- dask-labextension
- nbstripout
- jupyter-server-proxy
- sphinx
- doc8
- pymunge
- climtas>=0.3.3 # pin to force update
- asyncssh
- ants
- xhistogram
- cartopy_userconfig=1.0.gadi
- geopy
- ninja
- hvplot
- cython
- esmf>=8.0.1=mpi_openmpi*
- esmpy>=8.0.1=mpi_openmpi*
- xesmf>=0.6.2 # https://github.com/pangeo-data/xESMF/issues/127
- sharppy
- docrep
- earthpy
- descartes
- era5grib>=0.3.9 # pinned to force update
- conda-tree
- xmitgcm
- cupy
- rioxarray
- rasterstats
- windrose
- pyam
- pyarrow
- python-gist
- celluloid
- jags
- xarray-spatial
- noise # unlisted dependency of xarray-spatial
- nctoolkit
- geoplot
- dask-ml>=2022.5.27
- mamba
- intake-esm==2023.1.6  #<2022.9.18  # downgrading until intake 0.6.6 issue solved
- pykrige
- nci_intake_catalogue>=1.3 # triggering update 
- cmdline_provenance
- mplleaflet
- branca
- fiona
- folium
- black
- aiohttp
- aiohttp-cors
- autopep8
- spyder-kernels
- dask-xgboost
- git-subtree
- xarray-spatial
- watermark
- cvxpy
- rechunker
- xmovie
- pymannkendall
- param
- tensorflow>=2.6 # pinned for solver stability
- shap 
- gh
- pyqt
- vtk
- mayavi
- gcm_filters
- timezonefinder
- lftp
- xarraymannkendall
- watchdog  
- numpy_groupies
- anytree
- fortran-language-server
- hdbscan
- jupyter-book
- iris-grib
- s3fs
- kerchunk
- ujson
- intake-thredds
- cafaz
- cdms2
- pygam
- pysal
- xmhw>=0.9.3
- argopy
- dataclasses-json
- ilamb
- posix_ipc
- spectrum
- arch-py
- pyextremes
- ipdb
- palettable
- webcolors
- mpl-scatter-density
- benchcab>=1.0
- lmfit
- xclim
- jupyter-resource-usage
- acs_replica_intake
- matchpy
- pytmatrix  
- mscorefonts
- opencv  
- conda-build
- conda-verify
- pygmt
- gmt
- greenlet ### Dependency of... something?
- objgraph ### Unlisted dependency of greenlet
- xarrayutils
- wradlib
- pyinterp
- wavespectra
- xmip
- xcdat
- neutralocean
- ipympl
- libtiff<4.5.0 ### 4.4.0 -> 4.5.0 ABI change breaks gdal
- xskillscore
- geocat-comp
- ecgtools
- gcc_linux-64>=12.2.0 ### Pin otherwise parcels brings in a very old version that breaks the module file
- ipywidgets>=8
- flox
- erddapy>2 ### Pin to fix argopy bringing in very old version of erddapy
- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing
