name: analysis3
channels:
- coecms
- conda-forge
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/hh5/public/apps/cartopy-data/backgrounds
dependencies:
- python>=3.8
- coecms-nci
- cdo
- hdf5
 #x basemap # Deprecated, see https://matplotlib.org/basemap/users/intro.html#deprecation-notice
 #x basemap-data-hires
- cartopy
- dask
- distributed
- ipython
- iris
- netcdf4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- jupyter
- notebook
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh
- datashader
- f90nml
- wrf-python>=1.3.2.5
- sympy
- sh
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- compliance-checker
- dataset
- xerces-c
- plotly
- zarr
- pytables
- nose
- ncdu
- cftime<1.3.0 # Error with year=0 dates in 1.3.0
- memory_profiler
- fs
- python-magic
- click_default_group
- regionmask
- libgdal
- matplotlib
- dreqpy
- pint
- pycodestyle
- nc-time-axis
- jq
- pvlib-python
- parcels
- siphon
- scikit-learn
- filelock
- gsw
- nb_conda_kernels
- poppler
- fiona
- hupper
- kealib
- mo_pack
- mule
- cf-units
- python-stratify
- nbdime
- eofs
- eccodes>=2.21.0
- python-eccodes
- h5py
- line_profiler
- bottleneck
- jupyterlab
- dask-jobqueue
- jupyterlab_server
- docrep
- gifsicle
- jupyter_nbextensions_configurator
- nodejs
- cfgrib
- h5netcdf
- jupyter_contrib_nbextensions
- intake
# - pyngl # Needs recompiling with more recent gfortran?
# - pynio # Wants HDF5 < 1.10.6
- gridfill
# - pyferret # Needs recompiling with more recent gfortran?
- xgcm>=0.5
- xrft
- doit
- pylint
- dusqlpg
- matplotlib-venn
- nchash
- umtools
- cosima-cookbook
- clef
- nccmp
- coecms-util
- yamanifest
- cmocean
- payu>=1.0.20
- splitvar
- marineHeatWaves
- holoviews
- pytest-cov
- panel
- xrft
- git
- openmpi
- mpi4py
- palettable
- xlrd
  #- pybufr-ecmwf # Error compiling for python 3.7
- nccompress
- mdssdiff
- mnctools
- addmeta
- satpy
- statsmodels
- dask-labextension
- nbstripout
- jupyter-server-proxy
- sphinx
- doc8
- pymunge
- climtas
- asyncssh
- ants
- xhistogram
- cartopy_userconfig=1.0.gadi
- geopy
- ninja
- hvplot
- cython
- esmf>=8.0.1=mpi_openmpi*
- esmpy>=8.0.1=mpi_openmpi*
- xesmf
- sharppy
- docrep
- earthpy
- descartes
- era5grib
- conda-tree
- xmitgcm
- cupy
- rioxarray
- rasterstats
- windrose
- pyam
- pyarrow
- python-gist
  #- celluloid
- jags
- xarray-spatial
- nctoolkit
- geoplot
- dask-ml
- mamba
- intake-esm
- pykrige
- nci_intake_catalogue
- cmdline_provenance=1.0.0
- mplleaflet
- branca
- fiona
- folium
- black
- aiohttp
- aiohttp-cors
- autopep8
- spyder-kernels
- sqlalchemy<1.4
- tenacity<7.0.0
- dask-xgboost
