name: analysis27
channels:
- coecms
- conda-forge
- scitools
dependencies:
- python=2
- basemap
- bsddb
- cartopy
- dask
- ipython
- iris
- netCDF4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- pybufr-ecmwf
- jupyter
- nb_conda
- metpy
- windspharm
- cdat-lite
- python-cdo
- arm_pyart
- bokeh
- datashader
- arccssive
- pyferret
- f90nml
- wrf-python
- sympy
- sh
- basemap-data-hires
- ffmpeg
- pydap
- twine
- mule
- python-graphviz
- joblib
- tqdm
- gdal
- umtools
- dataset
- cfchecker
- compliance-checker
