name: analysis3
channels:
- coecms
- conda-forge
dependencies:
- python>=3.7
- coecms-nci
- cdo
- hdf5
  #- basemap # Deprecated, see https://matplotlib.org/basemap/users/intro.html#deprecation-notice
- cartopy
- dask
- distributed
- ipython
- iris>=2.2.1
- netCDF4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- jupyter
- notebook
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh
- datashader
- f90nml
- wrf-python
- sympy
- sh
  # - basemap-data-hires
- dataset
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- compliance-checker
- xerces-c
- plotly
- zarr
- pytables
- nose
- ncdu
- cftime
- memory_profiler
- fs
- python-magic
- click_default_group
- regionmask
- libgdal
- matplotlib
- dreqpy
- pint
- pycodestyle
- nc-time-axis
- jq
- pvlib-python
- parcels
- siphon
- scikit-learn
- filelock
- gsw
- nb_conda_kernels
- poppler
- fiona>1.8
- sanic 
- hupper
- kealib
- mo_pack
- mule
- cf_units
- python-stratify
- nbdime
- eofs
- python-eccodes
- h5py
- line_profiler
- bottleneck
- jupyterlab
- dask-jobqueue
- jupyterlab_server
- docrep
- gifsicle
- jupyter_nbextensions_configurator
- nodejs
- cfgrib
- h5netcdf
- jupyter_contrib_nbextensions
- intake
- pyngl
- pynio
- gridfill
- pyferret
- xgcm
- xrft
- doit
- pylint
- dusqlpg
- matplotlib-venn
- ncimonitor=0.3.6   # Pin to this version for general NCI use. Later versions are for grafana
- nchash
- umtools
- cosima-cookbook
- clef
- nccmp
- coecms-util
- yamanifest
- cmocean
- payu
- splitvar
- marineHeatWaves
- holoviews
- pytest-cov
- panel
- xrft
- git
- openmpi=4.0.1.gadi # Loads openmpi module on gadi
- mpi4py
- palettable
- xlrd
  #- pybufr-ecmwf # Error compiling for python 3.7
- nccompress
- mdssdiff
- mnctools
- addmeta
- satpy
- statsmodels>=0.11.0
- dask-labextension
- nbstripout
- jupyter-server-proxy
- sphinx
- doc8
- pymunge
- climtas
- asyncssh
- ants
- xhistogram
